### ISSUE TITLE
Request disposed in authentication middleware

### ISSUE THREAD

**Issue by danjohnso** [autofac/Autofac.Mvc#11]
I'm trying to resolve a registered service in my CookieAuthenticationProvider but it complains about the scope already being disposed.  Seems like this shouldn't be disposed yet or there should be a way to retrieve the service without registering it as a singleton.

**Error:**  Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed.

```
...
Provider = new CookieAuthenticationProvider
{
    OnResponseSignedIn = async (CookieResponseSignedInContext context) =>
    {
        IProfileService profileService = AutofacDependencyResolver.Current.GetService<IProfileService>();
...
```

**Comment by alexmg** [comment]
Does `AutofacDependencyResolver.Current.RequestLifetimeScope.Resolve<IProfileService>()` work for you?

**Comment by danjohnso** [comment]
No, the RequestLifetimeScope is marked as disposed already.

**Comment by tillig** [comment]
Can you post a small repro of the issue if it's still happening? It would help to debug into things and see what's going on.

My initial guess has something to do with the `async/await` I see in there since I've had all sorts of trouble with async operations losing the current request context and such.

**Comment by tillig** [comment]
I'm going to close this for now since there's no repro. If we can get a repro to see what's going on in action, we may be able to re-open. It also may be good to ask [on StackOverflow](http://stackoverflow.com) and tag it `autofac` to see if others in the community may have already seen this and figured it out.

**Comment by danjohnso** [comment]
@tillig sorry for the late response, was out of town for a few days.  I created an empty mvc project with just a simple service injection that repros this, async or sync doesn't matter.  I worked around this by using the sign in manager to take care of the claims for now, but I would rather do my work within the provider context.
https://github.com/danda1man/CookieAuth.Autofac/tree/master

**Comment by tillig** [comment]
Did you ask the question on StackOverflow? I will reopen the issue, but you will probably get a faster response by opening the ability to answer up to the community.

**Comment by danjohnso** [comment]
Just posted on SO: http://stackoverflow.com/questions/38508635/autofac-request-disposed-in-authentication-middleware

I will report back if I get any answers

**Comment by tillig** [comment]
If we get a chance to take a look, we'll update the SO question so the community can benefit from the answer as well. Thanks!
